### ISSUE TITLE
Crypto Mining on the extension

### ISSUE THREAD

**Issue by mariopoeta** [run-at-scale/vscode-terraform-doc-snippets#6]
# I have issues

User mario.pereira attempted to sav \My Documents\extensions\.run-at-scale.terraform-doc-snippets-0.3.0\node_modules\nodegit\vendor\libssh2\docs\HACKING.CRYPTO to E:\ on the server. This file is in the "Cryptolockers" file group, which is not permitted on the server.

## I'm submitting a

* [ ] bug report

## If this is a bug, how to reproduce? Please include a code sample

Crypto Mining on the extension

## What's the expected behavior

Crypto Mining on the extension

## Environment

* Affected module version:
* OS:
* Terraform version:

**Comment by brandoconnor** [comment]
Hi @mariopoeta . I see you concern but what software alerted you to this problem? To be clear, if this is an issue, it's with the dependent node modules, nodegit or more specifically libssh2, both of which are well supported and I would trust to not have crypto mining within them (github's [dependency security scanner](https://github.com/run-at-scale/vscode-terraform-doc-snippets/network/dependencies) sees no issue with them).

Looking at the file in question for the version currently shipped (https://github.com/nodegit/nodegit/blob/6ff67a883c66a1cee23feb53b5f82c36c8a4df04/vendor/libssh2/docs/HACKING.CRYPTO) this file hasn't changed since Sept 2017. I think your scanner has mistaken this file as a threat based solely on its name on not on it being an actual risk. Can you show me what part of the code in question does any mining?

If you think this is still an issue, definitely open an issue with those dependent repos. Otherwise, if you find this was a false alarm, I'd appreciate a revised review on the VSCode marketplace 👍

**Comment by mariopoeta** [comment]
Hi Brandon,

Thank you for your quick reply.

Well, short history, it was detected by our antivirus system and my Security guy started panicking, 

Review removed and issue closed. However, i think the name of the file would cause more false alarms. :P

**Comment by brandoconnor** [comment]
Not a problem and thanks for the quick follow up. Always good to know folks like you have their eyes on security and are willing to report issues. 🙇
